version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gyani_postgres
    environment:
      POSTGRES_DB: gyanibot_db
      POSTGRES_USER: gyaniuser
      POSTGRES_PASSWORD: gyanipass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
