version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gyani_postgres
    environment:
      POSTGRES_DB: gyanibot_db
      POSTGRES_USER: gyaniuser
      POSTGRES_PASSWORD: gyanipass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gyanibot-net

  mongo:
    image: mongo:latest
    container_name: gyani_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - gyanibot-net

volumes:
  postgres_data:
  mongo_data:

networks:
  gyanibot-net:
    driver: bridge
