apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://gyani_prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://gyani_loki:3100
